pid: /var/vcap/sys/run/uaa.pid
mbus: nats://localhost:4222
oauth:
  client:
    override: true
    autoapprove:
      - cf
  clients:
    cf:
      override: true
      authorized-grant-types: password,implicit
      authorities: uaa.none
      scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
    srest:
      override: true
      secret: 'changeme'
      authorized-grant-types: client_credentials
      authorities: uaa.resource,cloud_controller.admin
    cloud_controller:
      override: true
      secret: cloudcontrollersecret
      authorized-grant-types: client_credentials
      authorities: scim.read,scim.write
      scope: uaa.none
jwt:
  token:
    signing-key: 'tokensecret'
    verification-key: 'tokensecret'
scim:
  userids_enabled: false
  user.override: true
  users:
    - admin|password|scim.write,scim.read,openid,cloud_controller.admin
